import { allBrand, CategoryType, Itemlist, unit, category } from "./placeholder-data";

export interface hardItemList extends Itemlist {
    brand: allBrand,
    type: CategoryType,
    category: category,
    disclaimer?: string,
    productInformation?: {
        type: category,
        shellLife: string,
        storageTemperature?: string,
        container?: string
    }
}
//making the the unit secondary and primary is used only in the item nothing extra
// carton - having a different item inits own

const vegetableList: hardItemList[] = [
    {
        name: "Tomato",
        imageURL: "/categories-item/vegetable/tomato.png",
        buttonURL: "/item/tomato",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 30,
        discountValue: 18,
        savingAmount: 0,
        offers: [{ price: 15, quantity: 10, unit: unit.kg }],
        unit: unit.kg,
        secondaryUnit: unit.none,
        outOfStock: false,
        type: { all: "all", vegetable: "tomato , potato & onion" },
        brand: "generic",
        category: "vegetable",
        maxOrder: 100,
         disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "10-15 ˚C",
        container: "polythene"
    }
    },
    {
        name: "Potato",
        imageURL: "/categories-item/vegetable/potato.png",
        buttonURL: "/item/potato",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        secondaryUnit: unit.none,
        mrp: 25,
        discountValue: 17,
        savingAmount: 0,
        offers: [{ price: 14, quantity: 25, unit: unit.kg }],
        unit: unit.kg,
        type: { all: "all", vegetable: "tomato , potato & onion" },
        outOfStock: false,
        category: "vegetable",
        brand: "generic",
        maxOrder: 100,
            disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "20-25 ˚C",
        container: "polythene"
    }
    },
    {
        name: "Onion",
        imageURL: "/categories-item/vegetable/onion.png",
        buttonURL: "/item/onion",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 30,
        discountValue: 19,
        savingAmount: 500,
        offers: [{ price: 40, quantity: 100, unit: unit.kg }],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", vegetable: "tomato , potato & onion" },
        outOfStock: false,
        category: "vegetable",
        maxOrder: 100    ,disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "20-30 ˚C",
        container: "polythene"
    }

    },
    {
        // difference between the secondary and primary size i.e conversion
        name: "Carrot",
        imageURL: "/categories-item/vegetable/carrot.png",
        buttonURL: "/item/carrot",
        quantity: 0.5,
        primarySize: 0.5,
        secondarySize: 0,
        mrp: 60,
        discountValue: 42,
        savingAmount: 18,
        offers: [{ price: 35, quantity: 5, unit: unit.kg }, { price: 250, quantity: "1", unit: unit.bag, type: "bag" }],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        conversionRate: 2,
        type: { all: "all", vegetable: "indian vegetable" },
        outOfStock: false,
        category: "vegetable",
        maxOrder: 100, disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "10-15 ˚C",
        container: "polythene"
    }

    },
    {
        name: "Cabbage",
        imageURL: "/categories-item/vegetable/cabbage.png",
        buttonURL: "/item/cabbage",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 20,
        discountValue: 9,
        savingAmount: 11,
        offers: [{ price: 24, quantity: 8, unit: unit.kg }, { price: 50, quantity: 7, unit: unit.kg },],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", vegetable: "leafy vegetables" },
        outOfStock: false,
        category: "vegetable",
        maxOrder: 100,  disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "10-15 ˚C",
        container: "polythene"
    }

    },
    {
        name: "Garlic Peeled",
        imageURL: "/categories-item/vegetable/garlic_peeled.png",
        buttonURL: "/item/garlic_peeled",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 20,
        discountValue: 9,
        savingAmount: 11,
        offers: [{ price: 24, quantity: 8, unit: unit.kg }, { price: 50, quantity: 7, unit: unit.kg },],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", vegetable: "indian vegetable" },
        outOfStock: false,
        category: "vegetable",
        maxOrder: 100,     disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "20-25 ˚C",
        container: "polythene"
    }

    },
    {
        name: "orange carrot",
        imageURL: "/categories-item/vegetable/orange_carrot.png",
        buttonURL: "/item/orange_carrot",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 20,
        discountValue: 9,
        savingAmount: 11,
        offers: [{ price: 24, quantity: 8, unit: unit.kg }, { price: 50, quantity: 7, unit: unit.kg, superSaver: true },],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", vegetable: "indian vegetable" },
        outOfStock: false,
        category: "vegetable",
        maxOrder: 100 , disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "10-15 ˚C",
        container: "polythene"
    }

    },
    {
        name: "Indian Cucumber",
        imageURL: "/categories-item/vegetable/indian_cucumber.png",
        buttonURL: "/item/indian_cucumber",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 40,
        discountValue: 35,
        savingAmount: 0,
        offers: [{ price: 25, quantity: 10, unit: unit.kg }, { price: 30, quantity: 5, unit: unit.kg }, { price: 23, quantity: 15, unit: unit.kg, superSaver: true }],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", vegetable: "indian vegetable" },
        outOfStock: false,
        category: "vegetable",
        maxOrder: 100 , 
        disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "10-15 ˚C",
        container: "polythene"
    }

    }, {
        name: "Desi Tomato",
        imageURL: "/categories-item/vegetable/tomato.png",
        buttonURL: "/item/tomato",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 30,
        discountValue: 18,
        savingAmount: 0,
        offers: [{ price: 15, quantity: 10, unit: unit.kg }],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", vegetable: "tomato , potato & onion" },
        outOfStock: true,
        category: "vegetable",
        maxOrder: 100,    disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "10-15 ˚C",
        container: "polythene"
    }

    },
    {
        name: "Pahari aloo",
        imageURL: "/categories-item/vegetable/pahari_potato.png",
        buttonURL: "/item/pahari_potato",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        secondaryUnit: unit.none,
        mrp: 25,
        discountValue: 17,
        savingAmount: 0,
        offers: [{ price: 14, quantity: 25, unit: unit.kg }],
        unit: unit.kg,
        brand: "generic",
        type: { all: "all", vegetable: "tomato , potato & onion" },
        outOfStock: false,
        comingSoon: true,
        category: "vegetable",
        maxOrder: 100,    disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "10-15 ˚C",
        container: "polythene"
    }

    },
    {
        name: "Onion",
        imageURL: "/categories-item/vegetable/onion.png",
        buttonURL: "/item/onion",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 30,
        discountValue: 19,
        savingAmount: 500,
        offers: [{ price: 40, quantity: 100, unit: unit.kg }],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", vegetable: "tomato , potato & onion" },
        outOfStock: true,
        category: "vegetable",
        maxOrder: 100,     disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "20-35 ˚C",
        container: "polythene"
    }
    },
    {
        // difference between the secondary and primary size i.e conversion
        name: "Button Mushroom",
        imageURL: "/categories-item/vegetable/button_mushroom.png",
        buttonURL: "/item/button_mushroom",
        quantity: 1,
        primarySize: 1,
        secondarySize: 200,
        mrp: 60,
        discountValue: 42,
        savingAmount: 0,
        offers: [{ price: 35, quantity: 5, unit: unit.pkt }, { price: 32, quantity: "10", unit: unit.pkt }],
        unit: unit.pkt,
        brand: "generic",
        secondaryUnit: unit.gm,
        conversionRate: 200,
        type: { all: "all", vegetable: "exotic vegetables" },
        outOfStock: false,
        currentQuantity: 2,//hapeends in the preorder only
        category: "vegetable",
        maxOrder: 100,     
        disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "10-15 ˚C",
        container: "polythene"
    }

    },
    {
        name: "purple cabbage",
        imageURL: "/categories-item/vegetable/purple_cabbage.png",
        buttonURL: "/item/purple_cabbage",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 20,
        discountValue: 9,
        savingAmount: 11,
        offers: [{ price: 24, quantity: 8, unit: unit.kg }, { price: 50, quantity: 7, unit: unit.kg },],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.gm,
        type: { all: "all", vegetable: "exotic vegetables" },
        outOfStock: false,
        category: "vegetable",
        maxOrder: 100,    disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "10-15 ˚C",
        container: "polythene"
    }

    },
    {
        name: "ginger",
        imageURL: "/categories-item/vegetable/ginger.png",
        buttonURL: "/item/ginger",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 20,
        discountValue: 9,
        savingAmount: 11,
        offers: [{ price: 24, quantity: 8, unit: unit.kg }, { price: 50, quantity: 7, unit: unit.kg },],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", vegetable: "indian vegetable" },
        outOfStock: false,
        comingSoon: false,
        category: "vegetable",
        maxOrder: 100,    disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "10-15 ˚C",
        container: "polythene"
    }

    },
    {
        name: "red carrot",
        imageURL: "/categories-item/vegetable/red_carrot.png",
        buttonURL: "/item/red_carrot",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 20,
        discountValue: 9,
        savingAmount: 11,
        offers: [{ price: 24, quantity: 8, unit: unit.kg }, { price: 50, quantity: 7, unit: unit.kg },],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", vegetable: "indian vegetable" },
        outOfStock: true,
        category: "vegetable",
        maxOrder: 100,    disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "10-15 ˚C",
        container: "polythene"
    }

    },
    {
        name: "English Cucumber",
        imageURL: "/categories-item/vegetable/english_cucumber.png",
        buttonURL: "/item/english_cucumber",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 20,
        discountValue: 9,
        savingAmount: 11,
        offers: [{ price: 24, quantity: 8, unit: unit.kg }, { price: 50, quantity: 7, unit: unit.kg },],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", vegetable: "indian vegetable" },
        outOfStock: false,
        category: "vegetable",
        maxOrder: 100,    disclaimer: "The product may not be simlar to picture, the used picture is rather for general reference.",
    productInformation: {
        type: "vegetable",
        shellLife: "1 - 2 days",
        storageTemperature: "10-15 ˚C",
        container: "polythene"
    }

    },
]

const rationOilList: hardItemList[] = [
    {
        name: "Basmati Rice",
        imageURL: "/categories-item/ration-oil/basmati_rice.png",
        buttonURL: "/item/basmati_rice",
        quantity: 2.5,
        primarySize: 2.5,
        secondarySize: 0,
        mrp: 46,
        discountValue: 34,
        savingAmount: 0,
        offers: [{ price: 32, quantity: 20, unit: unit.kg, superSaver: true }],
        unit: unit.kg,
        brand: "India Gate",
        secondaryUnit: unit.none,
        type: { all: "all", ration_pluses_oil: "vanaspati & others" },
        outOfStock: false,
        category: "ration_pluses_oil",
        maxOrder: 100

    },
    {
        name: "Tur Dal",
        imageURL: "/categories-item/ration-oil/tur_dal.png",
        buttonURL: "/item/tur_dal",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 150,
        discountValue: 140,
        savingAmount: 10,
        offers: [{ price: 138, quantity: 5, unit: unit.kg }],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", ration_pluses_oil: "toor, kabuli & channa dal" },
        outOfStock: false,
        category: "ration_pluses_oil",
        maxOrder: 100

    },
    {
        name: "Sunflower Oil",
        imageURL: "/categories-item/ration-oil/sunflower_oil.png",
        buttonURL: "/item/sunflower_oil",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 160,
        discountValue: 157,
        savingAmount: 0,
        offers: [{ price: 10, quantity: 155, unit: unit.ltr }],
        unit: unit.ltr,
        brand: "Fortune",
        secondaryUnit: unit.none,
        type: { all: "all", ration_pluses_oil: "sunflower oil" },
        outOfStock: false,
        category: "ration_pluses_oil",
        maxOrder: 100

    },
    {
        name: "Sugar",
        imageURL: "/categories-item/ration-oil/sugar.png",
        buttonURL: "/item/sugar",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 60,
        discountValue: 46,
        savingAmount: 0,
        offers: [{ price: 10, quantity: 45.5, unit: unit.gm }],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", ration_pluses_oil: "vanaspati & others" },
        outOfStock: false,
        category: "ration_pluses_oil",
        maxOrder: 100

    },
    {
        name: "Vibhor Soyabean Oil",
        imageURL: "/categories-item/ration-oil/vibhor.png",
        buttonURL: "/item/vibhor_soyabean_oil",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 120,
        discountValue: 114,
        savingAmount: 0,
        offers: [{ price: 113, quantity: 10, unit: unit.ltr }],
        unit: unit.ltr,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", ration_pluses_oil: "soyabean oil" },
        outOfStock: false,
        category: "ration_pluses_oil",
        maxOrder: 100

    },
    {
        name: "Wheat Flour",
        imageURL: "/categories-item/ration-oil/wheat_flour.png",
        buttonURL: "/item/wheat_flour",
        quantity: 50,
        primarySize: 50,
        secondarySize: 0,
        mrp: 80,
        discountValue: 10,
        savingAmount: 0,
        offers: [{ price: 70, quantity: 50, unit: unit.gm }],
        unit: unit.kg,
        brand: "vanaspati",
        secondaryUnit: unit.none,
        type: { all: "all", ration_pluses_oil: "vanaspati & others" },
        outOfStock: false,
        category: "ration_pluses_oil",
        maxOrder: 100

    }
];
const dairyList: hardItemList[] = [
    {
        name: "Toned Milk",
        imageURL: "/categories-item/dairy/tone_milk.png",
        buttonURL: "/item/toned_milk",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 60,
        discountValue: 60,
        savingAmount: 0,
        offers: [],
        unit: unit.ltr,
        brand: "amul",
        secondaryUnit: unit.none,
        type: { all: "all", dairy: "milk & milk powder" },
        outOfStock: false,
        category: "dairy",
        maxOrder: 100

    },
    {
        name: "Amul Butter",
        imageURL: "/categories-item/dairy/amul_butter.png",
        buttonURL: "/item/amul_butter",
        quantity: 1,
        primarySize: 1,
        secondarySize: 500,
        mrp: 5500,
        discountValue: 500,
        savingAmount: 500,
        offers: [{ price: 5000, quantity: 500, unit: unit.gm }],
        unit: unit.pkt,
        brand: "amul",
        secondaryUnit: unit.gm,
        type: { all: "all", dairy: "butter" },
        outOfStock: false,
        category: "dairy",
        maxOrder: 100

    },
    {
        name: "Paneer",
        imageURL: "/categories-item/dairy/paneer2.png",
        buttonURL: "/item/paneer",
        quantity: 0.5,
        primarySize: 0.5,
        secondarySize: 0,
        mrp: 250,
        discountValue: 110,
        savingAmount: 0,
        offers: [{ price: 100, quantity: 250, unit: unit.gm }],
        unit: unit.gm,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", dairy: "paneer" },
        outOfStock: false,
        category: "dairy",
        maxOrder: 100

    },
    {
        name: "Curd",
        imageURL: "/categories-item/dairy/curd.png",
        buttonURL: "/item/curd",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 4000,
        discountValue: 500,
        savingAmount: 500,
        offers: [{ price: 3500, quantity: 1, unit: unit.ltr }],
        unit: unit.ltr,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", dairy: "curd" },
        outOfStock: false,
        category: "dairy",
        maxOrder: 100

    },
    {
        name: "Cheese Slices",
        imageURL: "/categories-item/dairy/cheese_slice.png",
        buttonURL: "/item/cheese_slice",
        quantity: 10,
        primarySize: 10,
        secondarySize: 0,
        mrp: 12000,
        discountValue: 1000,
        savingAmount: 1000,
        offers: [{ price: 11000, quantity: 10, unit: unit.pcs }],
        unit: unit.pcs,
        brand: "amul",
        secondaryUnit: unit.none,
        type: { all: "all", dairy: "cheese" },
        outOfStock: false,
        category: "dairy",
        maxOrder: 100

    }
]
    ;
const packagingList: hardItemList[] = [
    {
        name: "Plastic Bags Small",
        imageURL: "/categories-item/packaging-material/plastic_bags_small.png",
        buttonURL: "/item/plastic_bags_small",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 80,
        discountValue: 200,
        savingAmount: 200,
        offers: [{ price: 800, quantity: 100, unit: unit.pcs }],
        unit: unit.pcs,
        brand: "Biogreen",
        secondaryUnit: unit.none,
        type: { all: "all", "packaging-materials": "carry bags" },
        outOfStock: false,
        category: "packaging-materials",
        maxOrder: 100

    },
    {
        name: "Cardboard Box Large",
        imageURL: "/categories-item/packaging-material/cardboard_box_large.png",
        buttonURL: "/item/cardboard_box_large",
        quantity: 10,
        primarySize: 10,
        secondarySize: 0,
        mrp: 5000,
        discountValue: 500,
        savingAmount: 500,
        offers: [{ price: 4500, quantity: 10, unit: unit.pcs }],
        unit: unit.pcs,
        brand: "Ecopack",
        secondaryUnit: unit.none,
        type: { all: "all", "packaging-materials": "reusable containers" },
        outOfStock: false,
        category: "packaging-materials",
        maxOrder: 1000

    },
    {
        name: "Aluminum Foil",
        imageURL: "/categories-item/packaging-material/aluminium_foil.png",
        buttonURL: "/item/aluminum_foil",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 3000,
        discountValue: 500,
        savingAmount: 500,
        offers: [{ price: 2500, quantity: 1, unit: unit.pkt }],
        unit: unit.pkt,
        brand: "Hotpack",
        secondaryUnit: unit.none,
        type: { all: "all", "packaging-materials": "tapes, silverfoil & kitchen wraps" },
        outOfStock: false,
        category: "packaging-materials",
        maxOrder: 10

    },
    {
        name: "Paper Napkins",
        imageURL: "/categories-item/packaging-material/paper_napkin.png",
        buttonURL: "/item/paper_napkins",
        quantity: 10,
        primarySize: 10,
        secondarySize: 10,
        mrp: 2000,
        discountValue: 400,
        savingAmount: 400,
        offers: [{ price: 1600, quantity: 1, unit: unit.pkt }],
        unit: unit.pkt,
        brand: "Packman Packaging",
        secondaryUnit: unit.pcs,
        type: { all: "all", "packaging-materials": "cutlery & tissues" },
        outOfStock: false,
        category: "packaging-materials",
        maxOrder: 500

    },
    {
        name: "Garbage Bags",
        imageURL: "/categories-item/packaging-material/garbage_bags.png",
        buttonURL: "/item/garbage_bags",
        quantity: 2,
        primarySize: 2,
        secondarySize: 50,
        mrp: 3000,
        discountValue: 300,
        savingAmount: 300,
        offers: [{ price: 2700, quantity: 30, unit: unit.pcs }],
        unit: unit.pkt,
        brand: "Pactiv",
        secondaryUnit: unit.pcs,
        type: { all: "all", "packaging-materials": "carry bags" },
        outOfStock: false
        //it should not be here
        ,
        category: "packaging-materials",
        maxOrder: 100

    }
]
    ;
const masalaList: hardItemList[] = [
    {
        name: "Turmeric Powder",
        imageURL: "/categories-item/masala/turmeric_powder.png",
        buttonURL: "/item/turmeric",
        quantity: 200,
        primarySize: 200,
        secondarySize: 0,
        mrp: 4000,
        discountValue: 500,
        savingAmount: 500,
        offers: [{ price: 3500, quantity: 200, unit: unit.gm }],
        unit: unit.gm,
        brand: "kbm",
        secondaryUnit: unit.none,
        type: { all: "all", masala: "chilli, turmeric & coriander powder" },
        outOfStock: false,
        category: "masala"
    },
    {
        name: "Red Chili Powder",
        imageURL: "/categories-item/masala/chilli_powder.png",
        buttonURL: "/item/chili_powder",
        quantity: 100,
        primarySize: 100,
        secondarySize: 0,
        mrp: 500,
        discountValue: 100,
        savingAmount: 400,
        offers: [{ price: 80, quantity: 1000, unit: unit.kg }],
        unit: unit.kg,
        brand: "kbm",
        secondaryUnit: unit.none,
        type: { all: "all", masala: "chilli, turmeric & coriander powder" },
        outOfStock: false,
        category: "masala",
        maxOrder: 100

    },
    {
        name: "Coriander Powder",
        imageURL: "/categories-item/masala/coriander_powder.png",
        buttonURL: "/item/coriander_powder",
        quantity: 200,
        primarySize: 200,
        secondarySize: 0,
        mrp: 4500,
        discountValue: 700,
        savingAmount: 700,
        offers: [{ price: 3800, quantity: 200, unit: unit.gm }],
        unit: unit.gm,
        brand: "kbm",
        secondaryUnit: unit.none,
        type: { all: "all", masala: "chilli, turmeric & coriander powder" },
        outOfStock: false,
        category: "masala",
        maxOrder: 100

    },
    {
        name: "Black Pepper",
        imageURL: "/categories-item/masala/black-pepper.png",
        buttonURL: "/item/black_pepper",
        quantity: 100,
        primarySize: 100,
        secondarySize: 0,
        mrp: 9000,
        discountValue: 1000,
        savingAmount: 1000,
        offers: [{ price: 8000, quantity: 100, unit: unit.gm }],
        unit: unit.gm,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", masala: "whole spices" },
        outOfStock: false,
        category: "masala",
        maxOrder: 100

    },
    {
        name: "Iodized Salt",
        imageURL: "/categories-item/masala/iodized_salt.png",
        buttonURL: "/item/iodized_salt",
        quantity: 1000,
        primarySize: 1000,
        secondarySize: 0,
        mrp: 2000,
        discountValue: 200,
        savingAmount: 200,
        offers: [{ price: 1800, quantity: 1000, unit: unit.gm }],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", masala: "salt & sugar" },
        outOfStock: false,
        category: "masala",
        maxOrder: 100

    }
]
    ;
const riceFlourList: hardItemList[] = [
    {
        name: "Basmati Rice",
        imageURL: "/categories-item/rice-flours/basmati_rice.png",
        buttonURL: "/item/basmati_rice",
        quantity: 5,
        primarySize: 5,
        secondarySize: 0,
        mrp: 500,
        discountValue: 5000,
        savingAmount: 5000,
        offers: [{ price: 45000, quantity: 5, unit: unit.kg }],
        unit: unit.kg,
        brand: "India Gate",
        secondaryUnit: unit.none,
        type: { all: "all", "rice_flours": "rice" },
        outOfStock: false,
        category: "rice_flours",
        maxOrder: 100

    },
    {
        name: "Wheat Flour",
        imageURL: "/categories-item/rice-flours/wheat_flour.png",
        buttonURL: "/item/wheat_flour",
        quantity: 10,
        primarySize: 10,
        secondarySize: 0,
        mrp: 4000,
        discountValue: 2000,
        savingAmount: 2000,
        offers: [{ price: 1800, quantity: 10, unit: unit.kg }],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", "rice_flours": "flours" },
        outOfStock: false,
        category: "rice_flours",
        maxOrder: 100

    },
    {
        name: "Multigrain Atta",
        imageURL: "/categories-item/rice-flours/multigrain_atta.png",
        buttonURL: "/item/multigrain_atta",
        quantity: 5,
        primarySize: 5,
        secondarySize: 0,
        mrp: 600,
        discountValue: 5000,
        savingAmount: 5000,
        offers: [{ price: 55000, quantity: 5, unit: unit.kg }],
        unit: unit.kg,
        brand: "Aashirvaad",
        secondaryUnit: unit.none,
        type: { all: "all", "rice_flours": "flours" },
        outOfStock: false,
        category: "rice_flours",
        maxOrder: 100

    },
    {
        name: "Rice Flour",
        imageURL: "/categories-item/rice-flours/rice_flour.png",
        buttonURL: "/item/rice_flour",
        quantity: 2,
        primarySize: 2,
        secondarySize: 0,
        mrp: 1800,
        discountValue: 300,
        savingAmount: 1500,
        offers: [{ price: 150, quantity: 10, unit: unit.kg }],
        unit: unit.kg,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", rice_flours: "flours" },
        outOfStock: false,
        category: "rice_flours",
        maxOrder: 100

    },
    {
        name: "Maida",
        imageURL: "/categories-item/rice-flours/maida.png",
        buttonURL: "/item/maida",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 100,
        discountValue: 1500,
        savingAmount: 1500,
        offers: [{ price: 8500, quantity: 1, unit: unit.kg }],
        unit: unit.kg,
        brand: "AS",
        secondaryUnit: unit.none,
        type: { all: "all", rice_flours: "maida" },
        outOfStock: false,
        category: "rice_flours",
        maxOrder: 100

    }
]
    ;
const cleaningList: hardItemList[] = [
    {
        name: "Harpic Toilet Cleaner",
        imageURL: "/categories-item/cleaning-consumables/harpic.png",
        buttonURL: "/item/harpic",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 9500,
        discountValue: 1000,
        savingAmount: 1000,
        offers: [{ price: 8500, quantity: 1, unit: unit.ltr }],
        unit: unit.ltr,
        brand: "harpic",
        secondaryUnit: unit.none,
        type: { all: "all", cleaning_consumables: "toilet & bathroom cleaner" },
        outOfStock: false,
        category: "cleaning_consumables",
        maxOrder: 100

    },
    {
        name: "Vim Dishwash Bar",
        imageURL: "/categories-item/cleaning-consumables/vim_bar.png",
        buttonURL: "/item/vim_bar",
        quantity: 5,
        primarySize: 5,
        secondarySize: 0,
        mrp: 2500,
        discountValue: 500,
        savingAmount: 500,
        offers: [{ price: 2000, quantity: 5, unit: unit.pcs }],
        unit: unit.pcs,
        brand: "vim",
        secondaryUnit: unit.none,
        type: { all: "all", cleaning_consumables: "dishwash & detergents" },
        outOfStock: false,
        category: "cleaning_consumables",
        maxOrder: 100

    },
    {
        name: "Phenyl",
        imageURL: "/categories-item/cleaning-consumables/phenyl.png",
        buttonURL: "/item/phenyl",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 3000,
        discountValue: 300,
        savingAmount: 300,
        offers: [{ price: 2700, quantity: 1, unit: unit.ltr }],
        unit: unit.ltr,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", cleaning_consumables: "floor & glass cleaner" },
        outOfStock: false,
        category: "cleaning_consumables",
        maxOrder: 100

    },
    {
        name: "Broom Stick",
        imageURL: "/categories-item/cleaning-consumables/broom.png",
        buttonURL: "/item/broom",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 1200,
        discountValue: 200,
        savingAmount: 200,
        offers: [{ price: 1000, quantity: 1, unit: unit.pc }],
        unit: unit.pc,
        brand: "generic",
        secondaryUnit: unit.none,
        type: { all: "all", cleaning_consumables: "cleaning tools" },
        outOfStock: false,
        category: "cleaning_consumables",
        maxOrder: 100

    },
    {
        name: "Scrubber Pads",
        imageURL: "/categories-item/cleaning-consumables/scrubber_pad.png",
        buttonURL: "/item/scrubber_pad",
        quantity: 3,
        primarySize: 3,
        secondarySize: 0,
        mrp: 1500,
        discountValue: 30,
        savingAmount: 300,
        offers: [{ price: 1200, quantity: 3, unit: unit.pcs }],
        unit: unit.pcs,
        brand: "vim",
        secondaryUnit: unit.none,
        type: { all: "all", cleaning_consumables: "consumables" },
        outOfStock: false,
        category: "cleaning_consumables",
        maxOrder: 100

    }
]
    ;
const confectionaryList: hardItemList[] = [
    {
        name: "Ketchup Bottle",
        imageURL: "/categories-item/confectionary-sauces/ketchup.png",
        buttonURL: "/item/ketchup",
        quantity: 1,
        primarySize: 1,
        secondarySize: 1,
        mrp: 120,
        discountValue: 110,
        savingAmount: 2000,
        offers: [{ price: 100, quantity: 5, unit: unit.kg }],
        unit: unit.kg,
        brand: "kissan",
        secondaryUnit: unit.ltr,
        type: { all: "all", confectionary_sauces: "cheese blend & other sauces" },
        outOfStock: false,
        category: "confectionary_sauces"
    },
    {
        name: "Chocolate Bar",
        imageURL: "/categories-item/confectionary-sauces/chocolate_bar.png",
        buttonURL: "/item/chocolate_bar",
        quantity: 1,
        primarySize: 1,
        secondarySize: 0,
        mrp: 5000,
        discountValue: 50,
        savingAmount: 500,
        offers: [{ price: 4500, quantity: 1, unit: unit.pc }],
        unit: unit.pc,
        brand: "amul",
        secondaryUnit: unit.none,
        type: { all: "all", confectionary_sauces: "cheese blend & other sauces" },
        outOfStock: false,
        category: "confectionary_sauces",
        maxOrder: 100

    },
    {
        name: "Mayonnaise",
        imageURL: "/categories-item/confectionary-sauces/mayo.png",
        buttonURL: "/item/mayo",
        quantity: 250,
        primarySize: 250,
        secondarySize: 0,
        mrp: 900,
        discountValue: 100,
        savingAmount: 1500,
        offers: [{ price: 7500, quantity: 250, unit: unit.gm }],
        unit: unit.gm,
        brand: "freshy+",
        secondaryUnit: unit.none,
        type: { all: "all", confectionary_sauces: "cheese blend & other sauces" },
        outOfStock: false,
        category: "confectionary_sauces",
        maxOrder: 100

    },
    {
        name: "Jam Jar",
        imageURL: "/categories-item/confectionary-sauces/jam.png",
        buttonURL: "/item/jam",
        quantity: 50,
        primarySize: 500,
        secondarySize: 0,
        mrp: 130,
        discountValue: 30,
        savingAmount: 3000,
        offers: [{ price: 10000, quantity: 500, unit: unit.gm }],
        unit: unit.gm,
        brand: "yumsie",
        secondaryUnit: unit.none,
        type: { all: "all", confectionary_sauces: "cheese blend & other sauces" },
        outOfStock: false,
        category: "confectionary_sauces",
        maxOrder: 10

    },
    {
        name: "Chewing Gum Pack",
        imageURL: "/categories-item/confectionary-sauces/chewing_gum.png",
        buttonURL: "/item/chewing_gum",
        quantity: 1,
        primarySize: 10,
        secondarySize: 0,
        mrp: 40,
        discountValue: 20,
        savingAmount: 200,
        offers: [{ price: 1800, quantity: 10, unit: unit.pcs }],
        unit: unit.pcs,
        brand: "freshy+",
        secondaryUnit: unit.none,
        type: { all: "all", confectionary_sauces: "cheese blend & other sauces" },
        outOfStock: false,
        category: "confectionary_sauces",
        maxOrder: 10

    }
]
export const AllItems: Itemlist[] = [...vegetableList, ...rationOilList, ...dairyList, ...packagingList, ...masalaList, ...riceFlourList, ...cleaningList, ...confectionaryList]